# Generated by Django 4.0.4 on 2022-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=55)),
                ('prod_desc', models.CharField(max_length=2000)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
