# Generated by Django 4.0.4 on 2022-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
