# Generated by Django 4.0.4 on 2022-07-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_order_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Update',
        ),
    ]
